<h1>Blog Posts</h1>
<hr>
<div class="list-group">
  <table class="table">
    <tr>
      <th>Produto</th>
      <th></th>
    </tr>
    <?php foreach ($this->posts as $post): ?>

        <tr>
          <td><a href="<?= $this->url('blog/detail', ['id' => $post['id']]) ?>"> <?= $post['title'] ?></a></td>
          <td>
            <a class="btn btn-xs btn-default" href="<?= $this->url('blog/edit', ['id' => $post['id']]) ?>">Edit</a>
            <a class="btn btn-xs btn-danger" href="<?= $this->url('blog/delete', ['id' => $post['id']]) ?>">Delete</a>
          </td>
        </tr>

    <?php endforeach ?>
  </table>
</div>

<div class="btn-group" role="group" aria-label="Post actions">
  <a class="btn btn-primary" href="<?= $this->url('blog/add') ?>">Write new post</a>
</div>
